version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHANNEL_ACCESS_TOKEN=TOKEN
      - CHANNEL_SECRET=SECRET
      - MYSQL_HOST=mysql
      - MYSQL_USER=admin
      - MYSQL_PASS=password
    ports:
      - '3001:3000'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/docker/line-reminder-bot/db/data:/var/lib/mysql
      - ~/docker/line-reminder-bot/db/my.cnf:/etc/mysql/nginx.conf/my.cnf
      - ~/docker/line-reminder-bot/db/sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/ssl-cert/nginx.crt:/app/nginx.crt
      - ~/ssl-cert/nginx.key:/app/nginx.key
    ports:
      - '3000:3000'
