name: ssh-deploy
on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ssh key generate
        run: echo "$SSH_KEY" > key && chmod 600 key
        env:
          key: ${{ secrets.SSH_KEY }}
      - name: rsync
        run: rsync -acvz --delete -e ”ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no” ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:app/line-reminder-bot/
