name: ssh-deploy
on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: rsync
        run: rsync -acvz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:app/line-reminder-bot/
